#!/usr/bin/env bash
# Autonomyx Platform — Single-File Installer
# Usage:  curl -fsSL https://get.openautonomyx.com/install.sh | bash
# Or:     ./install.sh [--token YOUR_API_KEY] [--port 3001] [--no-service]
#
# What this does:
#   1. Detects your OS + architecture
#   2. Downloads the latest autonomyx-runner binary
#   3. Installs to /usr/local/bin/autonomyx-runner
#   4. Creates /etc/autonomyx/autonomyx.env (if not already present)
#   5. Installs a systemd service (Linux) or launchd plist (macOS)
#   6. Starts the service
#
# Requirements: curl or wget, tar, bash 4+
# Supports:     Linux x86_64, Linux aarch64, macOS x86_64, macOS arm64
#
# openautonomyx.com

set -euo pipefail

BINARY_NAME="autonomyx-runner"
INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
CONFIG_DIR="${CONFIG_DIR:-/etc/autonomyx}"
SERVICE_NAME="autonomyx"
GITHUB_REPO="agennext/agent-ide"
VERSION="${VERSION:-latest}"

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[autonomyx]${NC} $*"; }
success() { echo -e "${GREEN}[autonomyx]${NC} $*"; }
warn()    { echo -e "${YELLOW}[autonomyx]${NC} $*"; }
error()   { echo -e "${RED}[autonomyx]${NC} $*" >&2; exit 1; }

# ── Parse args ────────────────────────────────────────────────────────────────
TOKEN=""
PORT="${PORT:-3001}"
NO_SERVICE=false
PRODUCTION=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --token)       TOKEN="$2";       shift 2 ;;
        --port)        PORT="$2";        shift 2 ;;
        --no-service)  NO_SERVICE=true;  shift   ;;
        --production)  PRODUCTION=true;  shift   ;;
        --version)     VERSION="$2";     shift 2 ;;
        *) warn "Unknown flag: $1"; shift ;;
    esac
done

# ── Detect OS + arch ──────────────────────────────────────────────────────────
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"
case "$ARCH" in
    x86_64)  ARCH="x86_64"  ;;
    aarch64|arm64) ARCH="aarch64" ;;
    *) error "Unsupported architecture: $ARCH" ;;
esac
case "$OS" in
    linux)  OS="linux"   ;;
    darwin) OS="macos"   ;;
    *) error "Unsupported OS: $OS" ;;
esac

TARBALL="${BINARY_NAME}-${OS}-${ARCH}.tar.gz"

info "Autonomyx Platform Installer"
info "OS: ${OS} / Arch: ${ARCH} / Version: ${VERSION}"

# ── Check prerequisites ───────────────────────────────────────────────────────
check_cmd() { command -v "$1" &>/dev/null || error "Required: $1 (not found)"; }
check_cmd curl
check_cmd tar

# ── Download binary ───────────────────────────────────────────────────────────
if [[ "$VERSION" == "latest" ]]; then
    DOWNLOAD_URL="https://github.com/${GITHUB_REPO}/releases/latest/download/${TARBALL}"
else
    DOWNLOAD_URL="https://github.com/${GITHUB_REPO}/releases/download/v${VERSION}/${TARBALL}"
fi

# Allow local build as fallback
if [[ -f "packages/agent-runner/target/release/${BINARY_NAME}" ]]; then
    info "Using local release build (packages/agent-runner/target/release/${BINARY_NAME})"
    BINARY_SRC="packages/agent-runner/target/release/${BINARY_NAME}"
    USE_LOCAL=true
else
    USE_LOCAL=false
    info "Downloading ${TARBALL}..."
    TMP_DIR="$(mktemp -d)"
    trap "rm -rf ${TMP_DIR}" EXIT
    curl -fsSL "$DOWNLOAD_URL" -o "${TMP_DIR}/${TARBALL}" \
        || error "Download failed. Check your internet connection and try again."
    tar -xzf "${TMP_DIR}/${TARBALL}" -C "${TMP_DIR}"
    BINARY_SRC="${TMP_DIR}/${BINARY_NAME}"
fi

# ── Install binary ────────────────────────────────────────────────────────────
info "Installing ${BINARY_NAME} to ${INSTALL_DIR}..."
if [[ ! -w "${INSTALL_DIR}" ]]; then
    SUDO="sudo"
    warn "Needs sudo to write to ${INSTALL_DIR}"
else
    SUDO=""
fi

$SUDO install -m 755 "${BINARY_SRC}" "${INSTALL_DIR}/${BINARY_NAME}"
success "Binary installed: ${INSTALL_DIR}/${BINARY_NAME}"

# Print version
"${INSTALL_DIR}/${BINARY_NAME}" --version 2>/dev/null || true

# ── Create config directory ────────────────────────────────────────────────────
$SUDO mkdir -p "${CONFIG_DIR}"

# Create env file only if it doesn't exist (don't overwrite secrets)
ENV_FILE="${CONFIG_DIR}/autonomyx.env"
if [[ ! -f "${ENV_FILE}" ]]; then
    # Generate a random 64-char API key if none provided
    if [[ -z "$TOKEN" ]]; then
        TOKEN="$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 64 2>/dev/null || openssl rand -hex 32)"
    fi

    $SUDO tee "${ENV_FILE}" > /dev/null <<EOF
# Autonomyx Platform — Environment Configuration
# Generated by installer on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# KEEP THIS FILE SECURE — it contains your API key

# ── Security ──────────────────────────────────────────────────────────────────
GATEWAY_API_KEY=${TOKEN}
PRODUCTION=${PRODUCTION}

# ── Network ───────────────────────────────────────────────────────────────────
PORT=${PORT}
# AUTONOMYX_PUBLIC_URL=https://your-domain.com
# CORS_ALLOWED_ORIGINS=https://your-app.com,https://admin.your-app.com

# ── Identity ──────────────────────────────────────────────────────────────────
# AUTONOMYX_IDENTITY_KEY=<base64-encoded Ed25519 private key>
# AUTONOMYX_NODE_NAME=autonomyx-node-1

# ── Providers ─────────────────────────────────────────────────────────────────
# ANTHROPIC_API_KEY=sk-ant-...
# OPENAI_API_KEY=sk-...
# OLLAMA_BASE_URL=http://localhost:11434

# ── Rate limits ───────────────────────────────────────────────────────────────
RATE_LIMIT_RPM=60
AUTH_FAILURE_THRESHOLD=10
AUTH_BAN_SECS=300

# ── Observability ─────────────────────────────────────────────────────────────
RUST_LOG=agent_runner=info,tower_http=warn
# OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
EOF
    $SUDO chmod 600 "${ENV_FILE}"
    success "Config created: ${ENV_FILE}"
    if [[ -z "$TOKEN" ]]; then
        warn "No --token provided. Generated API key written to ${ENV_FILE}"
    fi
else
    warn "Config already exists: ${ENV_FILE} (not overwritten)"
fi

# ── Install service ───────────────────────────────────────────────────────────
if [[ "$NO_SERVICE" == "true" ]]; then
    info "Skipping service installation (--no-service)"
else
    case "$OS" in
        linux)
            if command -v systemctl &>/dev/null; then
                info "Installing systemd service..."
                $SUDO tee "/etc/systemd/system/${SERVICE_NAME}.service" > /dev/null <<EOF
[Unit]
Description=Autonomyx Platform
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
User=nobody
Group=nogroup
EnvironmentFile=${ENV_FILE}
ExecStart=${INSTALL_DIR}/${BINARY_NAME}
Restart=always
RestartSec=5
# Security hardening
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=/var/lib/autonomyx

[Install]
WantedBy=multi-user.target
EOF
                $SUDO systemctl daemon-reload
                $SUDO systemctl enable "${SERVICE_NAME}"
                $SUDO systemctl restart "${SERVICE_NAME}"
                success "Service started: systemctl status ${SERVICE_NAME}"
            else
                warn "systemd not found — start manually: ${INSTALL_DIR}/${BINARY_NAME}"
            fi
            ;;
        macos)
            PLIST="/Library/LaunchDaemons/com.autonomyx.runner.plist"
            info "Installing launchd service..."
            $SUDO tee "${PLIST}" > /dev/null <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>             <string>com.autonomyx.runner</string>
    <key>ProgramArguments</key>  <array><string>${INSTALL_DIR}/${BINARY_NAME}</string></array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>GATEWAY_API_KEY</key> <string>${TOKEN}</string>
        <key>PORT</key>            <string>${PORT}</string>
        <key>RUST_LOG</key>        <string>agent_runner=info</string>
    </dict>
    <key>RunAtLoad</key>         <true/>
    <key>KeepAlive</key>         <true/>
    <key>StandardOutPath</key>   <string>/var/log/autonomyx.log</string>
    <key>StandardErrorPath</key> <string>/var/log/autonomyx.error.log</string>
</dict>
</plist>
EOF
            $SUDO launchctl load "${PLIST}"
            success "Service started via launchd"
            ;;
    esac
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
success "Autonomyx Platform installed successfully!"
echo ""
echo "  Binary:     ${INSTALL_DIR}/${BINARY_NAME}"
echo "  Config:     ${ENV_FILE}"
echo "  Port:       ${PORT}"
if [[ -n "$TOKEN" ]]; then
echo "  API key:    ${TOKEN}"
echo ""
warn "Save your API key — it will not be shown again."
fi
echo ""
echo "  Test:       curl http://localhost:${PORT}/health"
echo "  Logs:       journalctl -u ${SERVICE_NAME} -f    (Linux)"
echo "  Docs:       https://openautonomyx.com"
echo ""
