// Headless canvas renderer — generates visual artifacts (PNG/SVG) from agent run data
// without a browser. Uses node-canvas + fabric for server-side rendering.
// Called by the /api/runs/:id/render endpoint or from CLI mode.
//
// Usage:
//   const png = await renderRunTrace(run);
//   fs.writeFileSync('trace.png', png);

import { AgentRun } from './types';

// Lazy-load — only available when node-canvas is installed
let fabric: any = null;
async function getFabric() {
    if (!fabric) {
        try {
            const { fabric: f } = await import('fabric/node');
            fabric = f;
        } catch {
            throw new Error('headless rendering requires: npm install canvas fabric');
        }
    }
    return fabric;
}

const COLORS = {
    thought:   '#60b0ff',
    tool_call: '#d0a030',
    observation:'#60d0a0',
    result:    '#40d040',
    error:     '#d04040',
    bg:        '#111111',
    border:    '#222222',
    text:      '#c0c0c0',
    muted:     '#555555',
};

/** Render a run trace as a PNG buffer. */
export async function renderRunTrace(run: AgentRun): Promise<Buffer> {
    const f = await getFabric();

    const W    = 800;
    const ROW  = 28;
    const PAD  = 16;
    const H    = Math.max(400, PAD * 2 + run.steps.length * ROW + 120);

    const canvas = new f.StaticCanvas(null, { width: W, height: H });
    canvas.backgroundColor = COLORS.bg;

    // Header
    const header = new f.Text(`Run: ${run.runId}`, {
        left: PAD, top: PAD,
        fontSize: 14, fontFamily: 'monospace',
        fill: '#80b0ff', fontWeight: 'bold',
    });
    const sub = new f.Text(`${run.agentName} · ${run.model} · ${run.status}`, {
        left: PAD, top: PAD + 20,
        fontSize: 11, fontFamily: 'monospace', fill: COLORS.muted,
    });
    const task = new f.Text(`Task: ${run.task.slice(0, 90)}${run.task.length > 90 ? '…' : ''}`, {
        left: PAD, top: PAD + 36,
        fontSize: 11, fontFamily: 'monospace', fill: COLORS.text,
    });
    canvas.add(header, sub, task);

    // Divider
    canvas.add(new f.Line([PAD, PAD + 56, W - PAD, PAD + 56], {
        stroke: COLORS.border, strokeWidth: 1,
    }));

    // Steps
    const stepY0 = PAD + 68;
    run.steps.forEach((step, i) => {
        const y    = stepY0 + i * ROW;
        const color = (COLORS as any)[step.type] ?? COLORS.muted;

        const dot = new f.Circle({ radius: 4, fill: color, left: PAD + 4, top: y + ROW / 2 - 4 });
        const typeLabel = new f.Text(step.type.padEnd(12), {
            left: PAD + 16, top: y + 6,
            fontSize: 10, fontFamily: 'monospace', fill: color,
        });
        const content = new f.Text(step.content.slice(0, 90), {
            left: PAD + 110, top: y + 6,
            fontSize: 10, fontFamily: 'monospace', fill: COLORS.text,
        });
        canvas.add(dot, typeLabel, content);
    });

    // Footer
    const footerY = H - PAD - 16;
    canvas.add(new f.Line([PAD, footerY - 8, W - PAD, footerY - 8], {
        stroke: COLORS.border, strokeWidth: 1,
    }));
    canvas.add(new f.Text(`Generated by Agent-IDE · ${new Date().toISOString()}`, {
        left: PAD, top: footerY,
        fontSize: 9, fontFamily: 'monospace', fill: COLORS.muted,
    }));

    canvas.renderAll();
    return (canvas as any).toBuffer('image/png') as Buffer;
}

/** Render a peer mesh topology as a PNG buffer. */
export async function renderMesh(peers: Array<{ name: string; url: string; status: string; }>): Promise<Buffer> {
    const f = await getFabric();
    const W = 600, H = 400;
    const canvas = new f.StaticCanvas(null, { width: W, height: H });
    canvas.backgroundColor = COLORS.bg;

    const cx = W / 2, cy = H / 2;
    const radius = 150;

    // Self node
    canvas.add(new f.Rect({ left: cx - 50, top: cy - 20, width: 100, height: 40, rx: 6, ry: 6, fill: '#0a1a2a', stroke: '#4080c0', strokeWidth: 2 }));
    canvas.add(new f.Text('this instance', { left: cx, top: cy, originX: 'center', originY: 'center', fontSize: 11, fontFamily: 'monospace', fill: '#80b0ff' }));

    peers.forEach((peer, i) => {
        const angle = (2 * Math.PI * i) / peers.length - Math.PI / 2;
        const px = cx + radius * Math.cos(angle);
        const py = cy + radius * Math.sin(angle);
        const color = { online: '#40d040', offline: '#d04040', unknown: '#555' }[peer.status] ?? '#555';

        canvas.add(new f.Line([cx, cy, px, py], { stroke: color === '#40d040' ? '#1a3a1a' : '#2a1a1a', strokeWidth: 1 }));
        canvas.add(new f.Rect({ left: px - 45, top: py - 18, width: 90, height: 36, rx: 4, ry: 4, fill: '#141414', stroke: color, strokeWidth: 1 }));
        canvas.add(new f.Text(peer.name.slice(0, 12), { left: px, top: py - 4, originX: 'center', originY: 'center', fontSize: 10, fontFamily: 'monospace', fill: '#c0c0c0' }));
        canvas.add(new f.Text(peer.status, { left: px, top: py + 8, originX: 'center', originY: 'center', fontSize: 8, fontFamily: 'monospace', fill: color }));
    });

    canvas.renderAll();
    return (canvas as any).toBuffer('image/png') as Buffer;
}
