apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agent-ide

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment-backend.yaml
  - deployment-ide.yaml
  - service-backend.yaml
  - service-ide.yaml
  - ingress.yaml
